#!/bin/sh

PYTHON=python3

D=`realpath $0`
cd `dirname ${D}`/..

WAIT_TO_KILL=60 # sec * 2 before kill -KILL

export ROBOGER_DIR=`pwd`

PIDFILE=${ROBOGER_DIR}/var/roboger.pid
ROBOGER=${ROBOGER_DIR}/sbin/roboger-server.py
ROBOGER_ARGS=
SAFE_RUN_PIDFILE=${ROBOGER_DIR}/var/roboger_safe.pid
SAFE_RUN=${ROBOGER_DIR}/sbin/safe-run.sh

case $1 in
start)
    echo 'Starting ROBOGER server'
    ${SAFE_RUN} ${SAFE_RUN_PIDFILE} ${PYTHON} ${ROBOGER} ${ROBOGER_ARGS} > /dev/null &
    ;;
launch)
    ${PYTHON} ${ROBOGER} ${ROBOGER_ARGS}
    ;;
stop)
    [ -f ${PIDFILE} ] || exit 1
    echo -n 'Stopping ROBOGER server '
    PID_SAFE_RUN=
    PID_ROBOGER=
    [ -f ${SAFE_RUN_PIDFILE} ] && PID_SAFE_RUN=`cat ${SAFE_RUN_PIDFILE}`
    [ -f ${PIDFILE} ] && PID_ROBOGER=`cat ${PIDFILE}`
    if [ "x${PID_SAFE_RUN}" != "x" ]; then
        kill ${PID_SAFE_RUN} > /dev/null 2>&1
        rm -f ${SAFE_RUN_PIDFILE}
    fi
    if [ "x${PID_ROBOGER}" != "x" ]; then
        kill ${PID_ROBOGER} > /dev/null 2>&1
        I=0
        while kill -0 ${PID_ROBOGER} > /dev/null 2>&1; do
            echo -n '.'
            sleep 0.5
            I=`expr ${I} + 1`
            if [ ${I} -ge ${WAIT_TO_KILL} ]; then
                echo -n  'killing '
                kill -KILL ${PID_ROBOGER}
                break
            fi
        done
        rm -f ${PIDFILE}
    fi
    echo ' stopped'
    ;;
restart)
    ./sbin/roboger stop $2
    ./sbin/roboger start $2
    ;;
logrotate)
    [ -f ${PIDFILE} ] && kill -HUP `cat ${PIDFILE}`
    ;;
version)
    ${PYTHON} ${ROBOGER} -V
    ;;
*)
    echo "Usage: roboger-control start|stop|restart|logrotate|version"
esac
